name: poem
description: Memorize poems quickly.
publish_to: none

version: 2.2.0+13

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  diacritic: ^0.1.3
  get_it:  ^7.2.0 
  intl: ^0.19.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  soundpool: ^2.3.0
  easy_localization: ^3.0.6
  flutter_app_badger: ^1.2.0
  path_provider: ^2.1.3
  share_plus: ^9.0.0
  file_picker: ^8.0.2
  charts_flutter:
    git:
      url: https://github.com/google/charts.git
      path: charts_flutter
  rate_my_app: ^2.1.0 
  flutter_riverpod: ^2.5.1
  
dependency_overrides:
  analyzer: ^1.0.0
  intl: ^0.19.0

dev_dependencies:   
  #hive_generator: ^1.1.0
  #build_runner: ^2.1.0  
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.11.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/sounds/click.mp3
    - assets/translations/en.json
    - assets/translations/sk.json
    - assets/poemsk.json
    - assets/poemen.json

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icona.png"  
  image_path_ios: "assets/icon/icon.png"  
  remove_alpha_ios: true 
